// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// Generated by script/art/chunks.py from script/art/data and script/art/swarm-v2.json: never edit by hand.

/// @notice Where Worker Frens' art sits. Chunks 0-6 are the IMD swarm's FrenArtChunk1..7 on Ethereum (its faces, hats
///         and items); chunks 7-8 are WorkerArt1..2 (the coat, item06, the backgrounds and the palettes).
///         INDEX: 5 bytes per entry (chunk, then offset and length in the chunk's art after its STOP byte, big-endian):
///         faces 0-38 (character * 13 + face), the coat 39, hats 40-41, items 42-56, backgrounds 57-68,
///         the shared palette 69 (entries 1..145), each background's own palette 70-81 (entries 146..).
library WorkerArtIndex {
    uint256 internal constant CHUNKS = 9;
    uint256 internal constant ENTRIES = 82;
    uint256 internal constant COAT = 39;
    uint256 internal constant HAT0 = 40;
    uint256 internal constant ITEM0 = 42;
    uint256 internal constant BG0 = 57;
    uint256 internal constant PALETTE = 69;
    uint256 internal constant BGPAL0 = 70;
    uint256 internal constant BACKGROUNDS = 12;
    /// @dev the shared palette's entries: 1..SHARED; a background's own start after
    uint256 internal constant SHARED = 145;
    /// @dev an unrevealed fren's background
    uint256 internal constant PENDING_BG = 7;
    /// @dev bit k set: chunk k keeps its art in frames, a PUSH32 byte before every 32 bytes
    uint256 internal constant FRAMED = 456;
    address internal constant SWARM_CHUNK1 = 0xa92dAcfF6d6fcC218ADe20eD24857376BD8eBE81;
    address internal constant SWARM_CHUNK2 = 0x9666A481e20F1dB59EEbD6c43D11Ae3505468c92;
    address internal constant SWARM_CHUNK3 = 0x71BdEB749b3ee428730eBB3E9b34B03A99D82356;
    address internal constant SWARM_CHUNK4 = 0x0C344484D960B8474a1EdcB5A5128e8D9C9F6B4d;
    address internal constant SWARM_CHUNK5 = 0x8734632850a8DFf2b18F49807AD321501A56906e;
    address internal constant SWARM_CHUNK6 = 0x11D5564E9d41ccbb4Fb92dF2D719282c90C959fD;
    address internal constant SWARM_CHUNK7 = 0xcfc3C7D69aEa5a4f8deA3105b66CF51cB63A12C0;
    /// @dev 5 bytes an entry (above), as hex text: the compiler may keep a constant as raw data after the code, which
    ///      IMD's admission scan reads as instructions; text can't show CALLCODE, DELEGATECALL or SELFDESTRUCT
    bytes internal constant INDEX =
        "000000068a00068a0676000d00069800139806bc001a5406b000210406820027860666002dec06a800349406a0003b340638"
        "00416c06640047d006dc004eac069200553e08820100000886010886087e01110408c60119ca088a0122540886012ada085a"
        "01333408ca013bfe08b40144b20872014d24087e0155a208a8020000088e02088e07820210100782021792078e021f2007b6"
        "0226d60782022e5807820235da0794023d6e07d002453e0792024cd00768025438077e03000007ae0307ae078a07000003a0"
        "03190a027e031b880200031d88011a031ea200a8031f4a0090031fda00e20320bc00c00703a000e0032258013403238c00e6"
        "03247200d203254400d203261600980326ae01520328000152032952008e0329e001160704800aaa070f2a0aaa0719d40aaa"
        "07247e0e740732f20e740741660e74074fda08800800000880080880088008110008800819800c340825b40c340831e80244"
        "08342c014408357001440836b401440837f8014408393c0144083a800144083bc40128083cec0128083e140128083f3c0128"
        "08406401b808421c01b8";
    /// @dev each chunk's code hash (keccak256 of its code), as hex text: the renderer reads only these exact chunks
    bytes internal constant CHUNK_HASHES =
        "f86a2decc7ef9279e69b3204890ef49c0099ea7a3b8b1a471019e23638fe2d4b8579d215b59ec2dbbae55d5dd85ebf64a69e"
        "529049a26e66401679b8666c650ed73ecfd95e853d3bf20224d02e30889477ac2627bc1970c5e6b0ca5ef202c9a854bd89d9"
        "6a8e4b1a1530687bb8442321920166014b5b7a89a414bae379f1a49bea0847b342ad6817321f26d81359a88dc124efa9c805"
        "36f3fa6bbf0af7582e4c73bde73579c30beebc346a7da3e86c0bb2bec3356b83feb3f55938b0de5e3a931925eee965d1ddd4"
        "ef8041b0f0a042304bebcc74ba605d1bb3bea5a0675cb700472e86951c7f637910c513b5056088530218c993d4f60de84a5d"
        "fca08ad2bc8c4b5307c2253c9d2f42fa70c43aab872ff7ee8a1e007ddcb0bb4225bf2f2ac04e";
    /// @dev lens 4x2, coat 3x5, shirt 6x2 (main, fold): shared palette indices
    bytes internal constant TABLES = hex"0102030405060708090a0b0c0d0e0f1011121314151617183f19401a411b6a1c6b1d6c";
}
