#!/usr/bin/env python3
"""Worker Frens' art, packed for the chain: what the swarm's launch adds to the art already there, and the index the
renderer reads both by.

The faces, the hats and 14 of the 15 items are the IMD swarm's, in its seven FrenArtChunk contracts on Ethereum
(swarm-v2.json): the renderer reads them where they are. What's new (script/art/data, from the art kit's export_v3.py):
the artist's coat, item06 redrawn, the 12 backgrounds, the shared palette and each background's own palette. That
goes into two data contracts the launch deploys, WorkerArt1 and WorkerArt2.

  python3 script/art/chunks.py

Writes:
  src/art/WorkerArt.sol        WorkerArt1, WorkerArt2: each one's code is a STOP byte, then the art (in frames if a raw
                               byte would read as CALLCODE, DELEGATECALL or SELFDESTRUCT to IMD's admission scan)
  src/art/WorkerArtIndex.sol   every entry the renderer draws (chunk, offset, length), the nine chunks' code hashes (both
                               as hex text), the swarm's chunk addresses, the colour tables
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "../.."))
DATA = os.path.join(HERE, "data")
m = json.load(open(os.path.join(DATA, "manifest.json")))
v2 = json.load(open(os.path.join(HERE, "swarm-v2.json")))
BGS = len(m["names"]["Background"])
S = m["shared"]
tables = open(os.path.join(DATA, "tables.bin"), "rb").read()
assert len(tables) == 35 and m["v2"]["faceTable"] == list(range(39))
layer = lambda n: open(os.path.join(DATA, "layers", n + ".bin"), "rb").read()
bgpal = [open(os.path.join(DATA, "bgpal", f + ".bin"), "rb").read() for f in m["bgPalettes"]]
assert all(len(p) <= 4 * (255 - S) for p in bgpal), "a background's palette runs past 255"

# The entries, in the renderer's order: (name, ("v2", layer) | ("new", bytes))
entries = [(f"face{i}", ("v2", f"face{i}")) for i in range(39)]
entries += [("coat", ("new", layer("coat")))]
entries += [(f"hat{h}", ("v2", f"hat{h}")) for h in range(2)]
entries += [(f"item{i}", ("new", layer("item5")) if i == 5 else ("v2", f"item{i}")) for i in range(15)]
entries += [(f"bg{b}", ("new", layer(f"bg{b}"))) for b in range(BGS)]
entries += [("palette", ("new", open(os.path.join(DATA, "shared.bin"), "rb").read()))]
entries += [(f"bgpal{b}", ("new", bgpal[b])) for b in range(BGS)]
POS = {n: i for i, (n, _) in enumerate(entries)}

# The new art into chunks: at most 23,808 bytes each, so even framed (33 bytes per 32) a chunk stays within EIP-170
CAP = 744 * 32
chunks, where, cur = [], {}, bytearray()
for n, (kind, b) in entries:
    if kind != "new":
        continue
    if len(cur) + len(b) > CAP:
        chunks.append(bytes(cur))
        cur = bytearray()
    where[n] = (7 + len(chunks), len(cur), len(b))
    cur += b
chunks.append(bytes(cur))
assert len(chunks) == 2, f"the launch deploys 2 art chunks, the art needs {len(chunks)}"

BAD = {0xF2, 0xF4, 0xFF}  # CALLCODE, DELEGATECALL, SELFDESTRUCT: what IMD's admission scan refuses, PUSH data skipped


def scan(code):
    i, hits = 0, 0
    while i < len(code):
        hits += code[i] in BAD
        if 0x60 <= code[i] <= 0x7F:
            i += code[i] - 0x5F
        i += 1
    return hits


def frame(c):
    """A PUSH32 byte before every 32 bytes of art (the last frame padded with zeros): a reader sees only PUSH data"""
    out = bytearray(b"\x00")
    for i in range(0, len(c), 32):
        blk = c[i:i + 32]
        out += b"\x7f" + blk + bytes(32 - len(blk))
    return bytes(out)


codes, framed = [], v2["framed"]
for k, c in enumerate(chunks):
    code = b"\x00" + c
    if scan(code):
        code = frame(c)
        framed |= 1 << (7 + k)
    assert scan(code) == 0 and len(code) <= 24576, (k, len(code))
    codes.append(code)

from Crypto.Hash import keccak as _k  # pycryptodome


def keccak(b):
    h = _k.new(digest_bits=256)
    h.update(b)
    return h.digest()


index = bytearray()
for n, (kind, b) in entries:
    c, off, ln = where[n] if kind == "new" else v2["entries"][b]
    assert off < 1 << 16 and ln < 1 << 16
    index += bytes([c]) + off.to_bytes(2, "big") + ln.to_bytes(2, "big")
hashes = b"".join(bytes.fromhex(h[2:]) for h in v2["codeHashes"]) + b"".join(keccak(c) for c in codes)
hexlines = lambda b, ind: "\n".join(f'{ind}hex"{b[i:i + 64].hex()}"' for i in range(0, len(b), 64))
textlines = lambda t, ind: "\n".join(f'{ind}"{t[i:i + 100]}"' for i in range(0, len(t), 100))

out = ["// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.26;", "",
       "// Generated by script/art/chunks.py from script/art/data: never edit by hand.", ""]
for k, (c, code) in enumerate(zip(chunks, codes), 1):
    how = (f"then {len(c)} bytes of art in frames: a PUSH32 byte before every 32 (WorkerArtIndex.FRAMED)"
           if framed >> (6 + k) & 1 else f"then {len(c)} bytes of art")
    out += [f"/// @notice Worker Frens' art, part {k} of {len(chunks)}: this contract's code is a STOP byte, {how}",
            "///         (WorkerArtIndex says what is where). Calling it does nothing.",
            f"contract WorkerArt{k} {{",
            "    constructor() {",
            "        bytes memory code =",
            hexlines(code, "            ") + ";",
            '        assembly ("memory-safe") {',
            "            return(add(code, 32), mload(code))",
            "        }",
            "    }",
            "}", ""]
open(os.path.join(ROOT, "src/art/WorkerArt.sol"), "w").write("\n".join(out))

swarm = "\n".join(f"    address internal constant SWARM_CHUNK{i + 1} = {a};" for i, a in enumerate(v2["chunks"]))
lib = f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// Generated by script/art/chunks.py from script/art/data and script/art/swarm-v2.json: never edit by hand.

/// @notice Where Worker Frens' art sits. Chunks 0-6 are the IMD swarm's FrenArtChunk1..7 on Ethereum (its faces, hats
///         and items); chunks 7-8 are WorkerArt1..2 (the coat, item06, the backgrounds and the palettes).
///         INDEX: 5 bytes per entry (chunk, then offset and length in the chunk's art after its STOP byte, big-endian):
///         faces 0-38 (character * 13 + face), the coat {POS["coat"]}, hats {POS["hat0"]}-{POS["hat1"]}, items {POS["item0"]}-{POS["item14"]}, backgrounds {POS["bg0"]}-{POS[f"bg{BGS - 1}"]},
///         the shared palette {POS["palette"]} (entries 1..{S}), each background's own palette {POS["bgpal0"]}-{POS[f"bgpal{BGS - 1}"]} (entries {S + 1}..).
library WorkerArtIndex {{
    uint256 internal constant CHUNKS = 9;
    uint256 internal constant ENTRIES = {len(entries)};
    uint256 internal constant COAT = {POS["coat"]};
    uint256 internal constant HAT0 = {POS["hat0"]};
    uint256 internal constant ITEM0 = {POS["item0"]};
    uint256 internal constant BG0 = {POS["bg0"]};
    uint256 internal constant PALETTE = {POS["palette"]};
    uint256 internal constant BGPAL0 = {POS["bgpal0"]};
    uint256 internal constant BACKGROUNDS = {BGS};
    /// @dev the shared palette's entries: 1..SHARED; a background's own start after
    uint256 internal constant SHARED = {S};
    /// @dev an unrevealed fren's background
    uint256 internal constant PENDING_BG = {m["pending"]["bg"]};
    /// @dev bit k set: chunk k keeps its art in frames, a PUSH32 byte before every 32 bytes
    uint256 internal constant FRAMED = {framed};
{swarm}
    /// @dev 5 bytes an entry (above), as hex text: the compiler may keep a constant as raw data after the code, which
    ///      IMD's admission scan reads as instructions; text can't show CALLCODE, DELEGATECALL or SELFDESTRUCT
    bytes internal constant INDEX =
{textlines(bytes(index).hex(), "        ")};
    /// @dev each chunk's code hash (keccak256 of its code), as hex text: the renderer reads only these exact chunks
    bytes internal constant CHUNK_HASHES =
{textlines(hashes.hex(), "        ")};
    /// @dev lens 4x2, coat 3x5, shirt 6x2 (main, fold): shared palette indices
    bytes internal constant TABLES = hex"{tables.hex()}";
}}
'''
open(os.path.join(ROOT, "src/art/WorkerArtIndex.sol"), "w").write(lib)
print("chunks", [len(c) for c in codes], "framed", [k + 1 for k in range(len(codes)) if framed >> (7 + k) & 1],
      "entries", len(entries), "new art", sum(len(c) for c in chunks))
